name: 🐛 Bug Report
description: Report a bug or issue with the project.
title: "[BUG] : "
labels: [bug]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
        Please fill out the form below to help us understand the issue.
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: >
        Provide a clear and concise description of the bug.
        Include any relevant information such as error messages, screenshots, or steps to reproduce.
      placeholder: |
        - What were you trying to do?
        - What did you expect to happen?
        - What actually happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 🔍 Steps to Reproduce
      description: >
        List the steps to reproduce the bug.
        Include any specific configurations or settings that are relevant.
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - 🟢 Low
        - 🟡 Medium
        - 🟠 High
        - 🔴 Critical
    validations:
      required: true
