name: ❓ Question
description: Ask a question or request clarification.
title: ""
labels: ["question"]
type: Question

body:
  - type: input
    id: question
    attributes:
      label: Your question
      description: Be as clear and specific as possible
      placeholder: What is the expected behavior of X?
